[tflite] make tflite related stuff build again on non-NNAPI platform
The NNAPI SL patch introduced using of `CreateNnApiFromSupportLibrary(NnApiSLDriverImplFL5 const*)` which caused a problem.

on macOS I got:
```
Undefined symbols for architecture x86_64:
  "CreateNnApiFromSupportLibrary(NnApiSLDriverImplFL5 const*)", referenced from:
      tflite::StatefulNnApiDelegate::StatefulNnApiDelegate(NnApiSLDriverImplFL5 const*, tflite::StatefulNnApiDelegate::Options) in libnnapi_delegate.a(nnapi_delegate.o)
      tflite::StatefulNnApiDelegate::StatefulNnApiDelegate(NnApiSLDriverImplFL5 const*, tflite::StatefulNnApiDelegate::Options) in libnnapi_delegate.a(nnapi_delegate.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

To fix this, I created an simple dummy function

see 4b949de5788a59ef2a300c57d02baffe24e330f0