fix TypeError in tensorflow/lite/python/convert.py
The error was preventing ROCm CI from completing, the error was
TypeError: a bytes-like object is required, not 'str'