Add grpc_cpp_plugin to the cmake build process
This fix adds grpc_cpp_plugin to the cmake build process
so that the following error could be fixed:

```
error: fatal error: tensorflow/core/debug/debug_service.grpc.pb.h: No such file or directory
```

This fix fixes 12018.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>