Hack/workaround for broken build
The following upstream commit breaks the open-source version on the TF build

https://github.com/tensorflow/tensorflow/commit/b1bb393072740da34071ed3e1b44a99506c7453b

The build fails with the following error

```
...
ImportError: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/create_tensorflow.python_api_tf_python_api_gen_v2.runfiles/org_tensorflow/tensorflow/python/platform/_pywrap_tf2.so: undefined symbol: _ZN10tensorflow4core6status13DerivedStatusC1Ev
...

```

It seems that the link error occurs because the above commit introduces a call to `tensorflow::core::status::DerivedStatus()` here ( https://github.com/tensorflow/tensorflow/commit/b1bb393072740da34071ed3e1b44a99506c7453b#diff-b0f683b75b92aeb08af2c777f88b9e8a7f20709457ae55c76d05293c75376c4cR268 ), but the library that contains the implementation for that routine is pulled in as "header only" here ( https://github.com/tensorflow/tensorflow/blob/b1bb393072740da34071ed3e1b44a99506c7453b/tensorflow/core/protobuf/BUILD#L196 )