Make @test_util.assert_no_new_pyobjects_executing_eagerly type aware.
Previously, it only checked the total objects count.  This is not ideal, for example,
it won't catch one less tuple object and one more Tensor object, which is likely an undesired leak.

Example error:
AssertionError: The following objects were newly created: Counter({'weakref': 1})
PiperOrigin-RevId: 278414654
Change-Id: I825633361e902b92e5f35e11451178b1b7eeae16