Adding `no_rocm` tag to //tensorflow/python/util:dispatch_test
This is an CPU test that started failing after the 210906 sync. This is a new test that was added this week by this commit

https://github.com/tensorflow/tensorflow/commit/fd04e309b8d80116ed13ba1b9b154e2ba1386f0c

Only subtest within it fails. It fails with the followin error

```
======================================================================
FAIL: testDispatchErrorForUnsupportedTypeAnnotation (__main__.DispatchV2Test)
DispatchV2Test.testDispatchErrorForUnsupportedTypeAnnotation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/util/dispatch_test.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 1236, in decorated
    f(self, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/util/dispatch_test.runfiles/org_tensorflow/tensorflow/python/util/dispatch_test.py", line 598, in testDispatchErrorForUnsupportedTypeAnnotation
    def my_add(x, y, name=None):  # pylint: disable=unused-variable
AssertionError: ValueError not raised

----------------------------------------------------------------------
Ran 48 tests in 1.108s

FAILED (failures=1, skipped=2)
================================================================================
```

Hoping this will get resolved upstream in a week or two, at which point we can remove the `no_rocm` from this test.