Removing TFRT targets from the do_bazel_nobuild step in the `Ubuntu-Sanity` CI run
With TFRT support currently being enabled only for Linux-CPU, attempts to build (even with the `--nobuild` option) any of the TFRT targets results in error. In particular the `do_bazel_nobuild` step in the `Ubuntu-Sanity` CI run (which is done with `--config=rocm`) essentially does the following

```
bazel build --config=rocm --nobuild  -- //tensorflow/... -//tensorflow/lite/...
```

and results in the following error

```
...
...
ERROR: /root/tensorflow/tensorflow/compiler/mlir/tfrt/jit/transforms/BUILD:24:18: no such package 'tensorflow/compiler/mlir/tfrt': Package is considered deleted due to --deleted_packages and referenced by '//tensorflow/compiler/mlir/tfrt/jit/transforms:tf_cpurt_passes_inc_gen_filegroup'
ERROR: /root/tensorflow/tensorflow/compiler/mlir/tfrt/jit/transforms/BUILD:24:18: no such package 'tensorflow/compiler/mlir/tfrt': Package is considered deleted due to --deleted_packages and referenced by '//tensorflow/compiler/mlir/tfrt/jit/transforms:tf_cpurt_passes_inc_gen_filegroup'
ERROR: Analysis of target '//tensorflow/compiler/mlir/tfrt/jit/transforms:tf_cpurt_passes_inc_gen_filegroup' failed; build aborted: Analysis failed
...
...

```

Therefore this commit updates the `do_bazel_nobuild` step, by adding the `-//tensorflow/compiler/mlir/tfrt/...` option to the `bazel build` command (issued within that step)