[ROCm] Fix for ROCM platform build breakage - 200123
The following build error started showing in the ROCm build (starting yesterday?)

```
ERROR: /root/tensorflow/tensorflow/compiler/xla/python/BUILD:115:1: C++ compilation of rule '//tensorflow/compiler/xla/python:shared_device_buffer' failed (Exit 1)
tensorflow/compiler/xla/python/shared_device_buffer.cc: In function 'void xla::PopulateShapedBufferFromBuffer(const xla::SharedDeviceBuffer&, xla::ShapeTree<stream_executor::DeviceMemoryBase>::iterator*, const iterator&)':
tensorflow/compiler/xla/python/shared_device_buffer.cc:156:52: error: 'const class stream_executor::DeviceMemoryBase' has no member named 'device_memory'
   for (const se::DeviceMemoryBase& buffer : buffer.device_memory()) {
                                                    ^
```

It can be reproduced by command `bazel build --config=rocm //tensorflow/compiler/xla/python:shared_device_buffer`

This commit fixes the breakage by renaming the loop variable to avoid the name ambiguity (which I suspect is the cause of the build error)