Fix python int overflow error.
The previous value triggers a python error:
```
OverflowError: int too big to convert
```
in python 3.10.  Reducing the value to one that fits in an int64 avoids the python
error while still causing the desired exception in the test.
PiperOrigin-RevId: 490010552