PR #13952: [XLA:GPU][AutoSharding] Enable autosharding in GPU compiler compilation
Imported from GitHub PR https://github.com/openxla/xla/pull/13952

## Objective:
This pull request aims to resolve compilation issues related to enabling GPU Auto Sharding functionality in the `auto_sharding_gpu_compiler_test.cc` file. fix #13612

## Background
When compiling the `auto_sharding_gpu_compiler_test.cc` using the command:

```shell
TF_CUDA_COMPUTE_CAPABILITIES="8.0" XLA_CUDA=1 bazel build xla/service/gpu:auto_sharding_gpu_compiler_test --config=cuda
```
While the compilation is successful, the unit test subsequently fails. Upon investigation, the failure seems to be linked to the following warning, which suggests that auto sharding is not enabled.

```shell
2024-06-19 17:44:19.985341: E xla/service/gpu/gpu_compiler.cc:552] GPU autosharding is not yet available in open source.
```
## Changes Made

1. To enable GPU Auto Sharding, I removed several conditional macros in `gpu_compiler.cc`. However, this modification led to a compilation error:
    ```shell
    xla/xla/service/gpu/BUILD:3402:11: Compiling xla/service/gpu/gpu_compiler.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target //xla/service/gpu:gpu_compiler) external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/xla/service/gpu/_objs/gpu_compiler/gpu_compiler.pic.d ... (remaining 519 arguments skipped)
    In file included from ./xla/hlo/experimental/auto_sharding/auto_sharding.h:37,
                     from xla/service/gpu/gpu_compiler.cc:253:
    ./xla/hlo/experimental/auto_sharding/auto_sharding_solver.h:25:10: fatal error: xla/hlo/experimental/auto_sharding/auto_sharding.pb.h: No such file or directory
       25 | #include "xla/hlo/experimental/auto_sharding/auto_sharding.pb.h"
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    ```

2. Upon reviewing the dependencies listed in the `BUILD` file for the `gpu_compiler` module, I discovered that the auto sharding module was not included. So I added the missing auto sharding module to the dependencies of the GPU compiler in the `BUILD` file.

## Results

Post-modification, the unit test now passes without errors, confirming that the changes fix the related issues.
Copybara import of the project:

--
71be6a3588a1d025f6ca75d9c1f53f78fb1645ff by luzhan <luzhan.lz@alibaba-inc.com>:

[XLA:GPU][AutoSharding] Enable autosharding in GPU compiler compilation

--
235bb7d9c211227cab3e32494c1d547bf8d1c3f2 by luzhan <luzhan.lz@alibaba-inc.com>:

fix: add ortools patch to enable compiling of torch/xla and tensorflow

Merging this change closes #13952

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/13952 from lausannel:main 235bb7d9c211227cab3e32494c1d547bf8d1c3f2
PiperOrigin-RevId: 645046991