Making the dependencies of `@cub_archive//:cub` conditional on `if_local_cuda`.
Starting with this week's weekly sync (210726), the CI Sanity test started failing with the following error

```
bazel query --noimplicit_deps -- -- 'deps(//tensorflow/... - kind("android_*", //tensorflow/...))'
...
...
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/cub_archive/BUILD.bazel:11:11: no such target '@local_cuda//:cuda_headers': target 'cuda_headers' not declared in package '' defined by /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/local_cuda/BUILD and referenced by '@cub_archive//:cub'
```

The cause seems to be change in TFRT repository which results `@cub_archive//:cub` target being picked up unconditionally via the following depenecy chain
```
//tensorflow/compiler/mlir/tfrt:bef_executor
@tf_runtime//tools:bef_executor_expensive_kernels
@tf_runtime//backends/gpu:gpu_tf_ops_alwayslink
@tf_runtime//backends/gpu:gpu_tf_ops
@tf_runtime//backends/gpu:tf_gpu_reduction_ops
@cub_archive//:cub
```

For ROCm the target `cuda_headers` does not exists, and hence (temporarily?) working around the error by making the dependencies of `@cub_archive//:cub` dependent of whether cuda is available locally