Java tests: Fix nightly builds.
For reasons not quite clear to me, the nightly builds (which are currently
using bazel 0.16.1) see failing Java tests with errors like:
  java.lang.NoSuchMethodError: java.nio.DoubleBuffer.flip()Ljava/nio/DoubleBuffer;
when calling "flip()" or "clear()" on a java.nio.DoubleBuffer object.

This is symptomatic of cross compiling in Java (e.g.
javac -source=1.9 -target=1.8) and this change works around that problem.

This does not happen with bazel 0.17.0 on the same test machine.
(Bringing me to the "reasons not quite clear to me" mentioned above).

PiperOrigin-RevId: 223643679