Rolling back the change that broke MacOS builds.
The error:

```
ERROR: .../tensorflow/python/BUILD:1528:15: Mandatory attribute 'actual' resolved to 'None' after evaluating 'select' expression
```

Reverts e1ca1524b415e43735dd872110c94638dedbcbd1

PiperOrigin-RevId: 810568791