Fix cmake build issue on Linux (#13145)
* Add grpc_cpp_plugin to the cmake build process

This fix adds grpc_cpp_plugin to the cmake build process
so that the following error could be fixed:

```
error: fatal error: tensorflow/core/debug/debug_service.grpc.pb.h: No such file or directory
```

This fix fixes 12018.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Fix cmake build error on Linux for sqlite.

This fix fixes cmake build error on Linux for sqlite

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Replace WIN32 with LIBJPEG_TURBO_VERSION for jpeg_mem.cc

This fix replace WIN32 with LIBJPEG_TURBO_VERSION for jpeg_mem.cc
so that cmake could build on Linux.

At the moment bazel uses libjpeg_turbo while CMAKE uses jpeg library
so it is necessary to pass different macros and build
separately on bazel/cmake.

Also add `#include <algorithm>` to fix build error.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>