Fix `invalid syntax` error when `import carla` is present
This fix tries to address the issue raised in 34828 where
`import carla` followed by `import tensorflow` caused the
following:
```
SyntaxError: invalid syntax
```

The issue is that, when `import carla` is invoked,
I/O operation for `std::ostringstream s` might fail,
which caused the conversion of AttrValue to string as empty.

This PR check `s.good()` to make sure the I/O operation
is OK, and, fallback to normal conversion if locale-neutral I/O
operation fails.

This PR fixes 34828.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>