Fix symbol duplication on Xcode/clang
Following linker error happened on Xcode:

```
duplicate symbol __Z14tf_git_versionv in:
    /Users/admin/tmp/tensorflow/tensorflow/contrib/ios_examples/simple/../../makefile/gen/lib/libtensorflow-core.a(version_info.o)
duplicate symbol __Z19tf_compiler_versionv in:
    /Users/admin/tmp/tensorflow/tensorflow/contrib/ios_examples/simple/../../makefile/gen/lib/libtensorflow-core.a(version_info.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

These functions are defined in `tensorflow/core/util/version_info.cc`.
It seems an object file for it is added twice in Makefile:
(`$(wildcard tensorflow/core/util/*.cc)` and `$(tensorflow/core/util/version_info.cc)
`)