Causes some windows tests to fail with
```
FAILED: //tensorflow/python/kernel_tests:cwise_ops_test (Summary)
      C:/tmp/hgi62d3r/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/python/kernel_tests/cwise_ops_test/shard_41_of_50/test.log
      C:/tmp/hgi62d3r/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/python/kernel_tests/cwise_ops_test/shard_41_of_50/test_attempts/attempt_1.log
      C:/tmp/hgi62d3r/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/python/kernel_tests/cwise_ops_test/shard_41_of_50/test_attempts/attempt_2.log
INFO: From Testing //tensorflow/python/kernel_tests:cwise_ops_test (shard 41 of 50):
==================== Test output for //tensorflow/python/kernel_tests:cwise_ops_test (shard 41 of 50):
Running tests under Python 3.8.3: c:\Python38\python.exe
[ RUN      ] MathOpsOverloadTest.testOverload
2020-08-07 18:06:36.702914: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-07 18:06:36.731707: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1f14f681f00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-07 18:06:36.732038: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:time(__main__.MathOpsOverloadTest.testOverload): 0.09s
I0807 18:06:36.788563  9040 test_util.py:1974] time(__main__.MathOpsOverloadTest.testOverload): 0.09s
No pending test case: __main__.MathOpsOverloadTest.testOverload
======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'power'>, tf_func=<function <lambda> at 0x000001F152FA13A0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_6r__ku2y\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_6r__ku2y\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'floor_divide'>, tf_func=<function <lambda> at 0x000001F152FA14C0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_6r__ku2y\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_6r__ku2y\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

----------------------------------------------------------------------
Ran 1 test in 0.093s

FAILED (errors=2)
================================================================================
==================== Test output for //tensorflow/python/kernel_tests:cwise_ops_test (shard 41 of 50):
Running tests under Python 3.8.3: c:\Python38\python.exe
[ RUN      ] MathOpsOverloadTest.testOverload
2020-08-07 18:07:02.741015: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-07 18:07:02.768942: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x177405cd170 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-07 18:07:02.769253: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:time(__main__.MathOpsOverloadTest.testOverload): 0.08s
I0807 18:07:02.821412  3188 test_util.py:1974] time(__main__.MathOpsOverloadTest.testOverload): 0.08s
No pending test case: __main__.MathOpsOverloadTest.testOverload
======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'power'>, tf_func=<function <lambda> at 0x0000017741FFF3A0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_1vkgaz40\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_1vkgaz40\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'floor_divide'>, tf_func=<function <lambda> at 0x0000017741FFF4C0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_1vkgaz40\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_1vkgaz40\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

----------------------------------------------------------------------
Ran 1 test in 0.087s

FAILED (errors=2)
================================================================================
==================== Test output for //tensorflow/python/kernel_tests:cwise_ops_test (shard 41 of 50):
Running tests under Python 3.8.3: c:\Python38\python.exe
[ RUN      ] MathOpsOverloadTest.testOverload
2020-08-07 18:07:22.498277: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-07 18:07:22.528039: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x18eee98a7e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-07 18:07:22.528627: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:time(__main__.MathOpsOverloadTest.testOverload): 0.07s
I0807 18:07:22.565276  5312 test_util.py:1974] time(__main__.MathOpsOverloadTest.testOverload): 0.07s
No pending test case: __main__.MathOpsOverloadTest.testOverload
======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'power'>, tf_func=<function <lambda> at 0x0000018EED9D13A0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_ruka25hh\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_ruka25hh\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

======================================================================
ERROR: testOverload (__main__.MathOpsOverloadTest) (dtype=tf.bfloat16, np_func=<ufunc 'floor_divide'>, tf_func=<function <lambda> at 0x0000018EED9D14C0>)
testOverload (__main__.MathOpsOverloadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_ruka25hh\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 883, in testOverload
    self._compareBinary(10, 5, dtype, np_func, tf_func)
  File "\\?\C:\Users\ContainerAdministrator\AppData\Local\Temp\Bazel.runfiles_ruka25hh\runfiles\org_tensorflow\tensorflow\python\kernel_tests\cwise_ops_test.py", line 843, in _compareBinary
    np_ans = np_func(x, y).astype(dtype.as_numpy_dtype)
ValueError: No cast function available.

----------------------------------------------------------------------
Ran 1 test in 0.074s
```

PiperOrigin-RevId: 325819709
Change-Id: I919270e31978573c652f88224a32beb55592aa84