Explicitly disable tfrt building+testing in the script to run `Ubuntu-CPU` unit-tests
Starting with the 210809 weekly sync, the following the unit-tests,  failed to build

```
//tensorflow/compiler/mlir/tfrt/tests:convert_ref_variables.mlir.test FAILED TO BUILD
//tensorflow/compiler/mlir/tfrt/tests:cross_device_transfer.mlir.test FAILED TO BUILD
//tensorflow/compiler/mlir/tfrt/tests:hoist_invariant_ops.mlir.test FAILED TO BUILD
//tensorflow/compiler/mlir/tfrt/tests:remote_run_encapsulate.mlir.test FAILED TO BUILD
//tensorflow/compiler/mlir/tfrt/tests:remove_device_attribute.mlir.test FAILED TO BUILD
```

with the following error

```
...
...
ERROR: /home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/tf_runtime/third_party/cuda/BUILD:6:12: Couldn't build file external/tf_runtime/third_party/cuda/include/cudart_stub.cc.inc: Executing genrule @tf_runtime//third_party/cuda:cudart_stub_inc failed (Exit 1): bash failed: error executing command
  (cd /home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow &&
  exec env - \
    LD_LIBRARY_PATH='' \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/k8-opt/bin/external/tf_runtime/backends/gpu/tools/stub_codegen/impl_codegen external/tf_runtime/backends/gpu/tools/stub_codegen/cudart.json bazel-out/k8-opt/bin/external/tf_runtime/third_party/cuda/include/cudart_stub.cc.inc')
Execution platform: @local_execution_config_platform//:platform
Traceback (most recent call last):
 File "/home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/k8-opt/bin/external/tf_runtime/backends/gpu/tools/stub_codegen/impl_codegen.runfiles/tf_runtime/backends/gpu/tools/stub_codegen/impl_codegen.py", line 24, in <module>
    import clang.cindex
ModuleNotFoundError: No module named 'clang'
...
...
...
```

Looks like support for TFRT requires the ability to build stub files from CUDA headers. This is something we need to investigate and find a way around. For the time being, simply changing the script to run `Ubuntu-CPU` uni-tests, to skip TFRT related stuff.