[ROCm] Fix for the broken `--config=rocm` build
The following PR/commit breaks the `--config=rocm` build

https://github.com/tensorflow/tensorflow/commit/fe5cf47131324d97239de65acb7a722381a0861d

```
./tensorflow/core/util/ctc/ctc_loss_calculator.h:451:22: error: no matching function for call to 'LogSumExp(const Scalar&, double)'
             LogSumExp(log_beta->coeff(u, t),
                      ^
In file included from ./tensorflow/core/util/ctc/ctc_loss_calculator.h:27:0,
                 from tensorflow/core/kernels/ctc_loss_op.cc:25:
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note: candidate: template<class T> T tensorflow::ctc::LogSumExp(T, T)
 inline T LogSumExp(T log_prob_1, T log_prob_2) {
          ^
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note:   template argument deduction/substitution failed:
In file included from tensorflow/core/kernels/ctc_loss_op.cc:25:0:
./tensorflow/core/util/ctc/ctc_loss_calculator.h:451:22: note:   deduced conflicting types for parameter 'T' ('float' and 'double')
             LogSumExp(log_beta->coeff(u, t),
                      ^
./tensorflow/core/util/ctc/ctc_loss_calculator.h:459:22: error: no matching function for call to 'LogSumExp(const Scalar&, double)'
             LogSumExp(log_beta->coeff(u, t),
                      ^
In file included from ./tensorflow/core/util/ctc/ctc_loss_calculator.h:27:0,
                 from tensorflow/core/kernels/ctc_loss_op.cc:25:
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note: candidate: template<class T> T tensorflow::ctc::LogSumExp(T, T)
 inline T LogSumExp(T log_prob_1, T log_prob_2) {
          ^
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note:   template argument deduction/substitution failed:
In file included from tensorflow/core/kernels/ctc_loss_op.cc:25:0:
./tensorflow/core/util/ctc/ctc_loss_calculator.h:459:22: note:   deduced conflicting types for parameter 'T' ('float' and 'double')
             LogSumExp(log_beta->coeff(u, t),
                      ^
./tensorflow/core/util/ctc/ctc_loss_calculator.h:471:24: error: no matching function for call to 'LogSumExp(const Scalar&, double)'
               LogSumExp(log_beta->coeff(u, t),
                        ^
In file included from ./tensorflow/core/util/ctc/ctc_loss_calculator.h:27:0,
                 from tensorflow/core/kernels/ctc_loss_op.cc:25:
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note: candidate: template<class T> T tensorflow::ctc::LogSumExp(T, T)
 inline T LogSumExp(T log_prob_1, T log_prob_2) {
          ^
./tensorflow/core/util/ctc/ctc_loss_util.h:36:10: note:   template argument deduction/substitution failed:
In file included from tensorflow/core/kernels/ctc_loss_op.cc:25:0:
./tensorflow/core/util/ctc/ctc_loss_calculator.h:471:24: note:   deduced conflicting types for parameter 'T' ('float' and 'double')
               LogSumExp(log_beta->coeff(u, t),

```

The error does not seem to be TF ROCm build specific, but it seems to manifest only on the TF ROCm build.

The fix is to explicitly cast the second argument of the call to the LogSumExp template instance (i.e. the return value of "log" function) to "float" instead of "double", thus removing the ambiguity for the template instantiation.