[Windows][MinGW] Fix build with mingw
Mingw's builtin header defines a function name which is used in xla, and causes an error. We undefined the macro here.

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/xla/xla/pjrt/gpu/tfrt/tfrt_gpu_client.cc:887:58: error: no member named 'CreateEventW' in 'stream_executor::StreamExecutor'; did you mean 'CreateEvent'?
  887 |     TF_ASSIGN_OR_RETURN(auto se_event, stream->parent()->CreateEvent());
      |                                                          ^~~~~~~~~~~
      |                                                          CreateEvent
/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/include/synchapi.h:145:21: note: expanded from macro 'CreateEvent'
  145 | #define CreateEvent __MINGW_NAME_AW(CreateEvent)
      |                     ^

PiperOrigin-RevId: 792697955