Revert "Add synthetic datasets (#5315)"
This reverts commit ca29fa3cc16663a8dddf5968b5600c60e2dc71a8.

Reason for rollback: Broke builds due to errors such as:

File
"/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py",
line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
    ImportError: cannot import name synthetic