Return to initialize_all_variables()
Return to initialize_all_variables() instead of global_variables_initializer() 
Got the following error while using global_variables_initializer:
AttributeError: 'module' object has no attribute 'global_variables_initializer'