Fix Jenkins build error (`//tensorflow/go:test`) on HEAD
This fix fixes Jenkins build error of `//tensorflow/go:test`
on HEAD:
```
FAIL: //tensorflow/go:test (see /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow/bazel-out/local-opt/testlogs/tensorflow/go/test/test.log).
INFO: From Testing //tensorflow/go:test:
==================== Test output for //tensorflow/go:test:
...
...
--- FAIL: TestNewTensor (0.00s)
	tensor_test.go:112: NewTensor([5]): <nil>
	tensor_test.go:115: NewTensor([5]) = &{0x7f71f4009e80 [1]}, want nil
	tensor_test.go:112: NewTensor([5]): <nil>
	tensor_test.go:115: NewTensor([5]) = &{0x7f71f400af10 [1]}, want nil
FAIL
FAIL	github.com/tensorflow/tensorflow/tensorflow/go	0.392s
ok  	github.com/tensorflow/tensorflow/tensorflow/go/op	0.138s
================================================================================
```

The error was introduced by 14368 as Uint32 and Uint64 has not been supported by
TensorFlow yet.

See Ln 74 of `tensorflow/go/tensor_test.go`
Compare Ln 334 and 316 of `tensorflow/go/tensor.go` before this PR.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>