[ROCm] Fix for a build failure on the ROCm platform - 200323 -
The following commit introduces a build error on the ROCm platform

https://github.com/tensorflow/tensorflow/commit/848a0666d4b9fb9fcb4d32192c7f3bc1c1702a41

build error

```
ERROR: /root/tensorflow/tensorflow/lite/kernels/BUILD:1747:1: Couldn't build file tensorflow/lite/kernels/_objs/pack_test/pack_test.o: C++ compilation of rule '//tensorflow/lite/kernels:pack_test' failed (Exit 1)
tensorflow/lite/kernels/pack_test.cc:198:31: error: expected ';' at end of member declaration
       std::is_same<InputType, int16_t>::value
                               ^
tensorflow/lite/kernels/pack_test.cc:198:38: error: expected unqualified-id before '>' token
       std::is_same<InputType, int16_t>::value
                                      ^
tensorflow/lite/kernels/pack_test.cc:198:20: error: wrong number of template arguments (1, should be 2)
       std::is_same<InputType, int16_t>::value
                    ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/memory:62,
                 from external/com_google_googletest/googletest/include/gtest/gtest.h:56,
                 from tensorflow/lite/kernels/pack_test.cc:15:
/usr/include/c++/5/type_traits:958:12: note: provided for 'template<class, class> struct std::is_same'
     struct is_same;
            ^
ERROR: /root/tensorflow/tensorflow/lite/kernels/BUILD:1789:1: Couldn't build file tensorflow/lite/kernels/_objs/unpack_test/unpack_test.o: C++ compilation of rule '//tensorflow/lite/kernels:unpack_test' failed (Exit 1)
tensorflow/lite/kernels/unpack_test.cc:90:31: error: expected ';' at end of member declaration
       std::is_same<InputType, int16_t>::value
                               ^
tensorflow/lite/kernels/unpack_test.cc:90:38: error: expected unqualified-id before '>' token
       std::is_same<InputType, int16_t>::value
                                      ^
tensorflow/lite/kernels/unpack_test.cc:90:20: error: wrong number of template arguments (1, should be 2)
       std::is_same<InputType, int16_t>::value
                    ^
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/memory:62,
                 from external/com_google_googletest/googletest/include/gtest/gtest.h:56,
                 from tensorflow/lite/kernels/unpack_test.cc:15:
/usr/include/c++/5/type_traits:958:12: note: provided for 'template<class, class> struct std::is_same'
     struct is_same;
            ^
                                      ^
```

The build error seems is similar to the one discussed in this PR https://github.com/tensorflow/tensorflow/pull/36558, and the fix is the same as well (adding parens around cond op expression)