Define StructuredTensor.FieldName outside the class.
Fixes a problem where structured_tensor fails to import under Python 3.14 with the error:

```
  File ".../tensorflow/python/ops/structured/structured_tensor.py", line 54, in <module>
    class StructuredTensor(extension_type.BatchableExtensionType):
    ...<1135 lines>...
          return self._ragged_shape.rank
  File ".../tensorflow/python/framework/extension_type.py", line 90, in __init__
    _check_field_annotations(cls)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File ".../tensorflow/python/framework/extension_type.py", line 935, in _check_field_annotations
    raise ValueError(
    ...<2 lines>...
    )
ValueError: The field annotations for StructuredTensor are invalid. Field FieldName is missing a type annotation.
```
PiperOrigin-RevId: 834982237