Fix build breaks in tf-nightly-2.0-preview
This fix tries to address the issue raised in 30560 where
tf-nightly-2.0-preview throws error:
```
ubuntu@ubuntu:/# python -c "import tensorflow as tf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/__init__.py", line 363, in <module>
    _API_MODULE = sys.modules[__name__].bitwise  # pylint: disable=undefined-variable
NameError: name 'sys' is not defined
ubuntu@ubuntu:/#
```

The issue was cause by the typo sys -> _sys in `tensorflow/api_template.__init__.py`

This fix fixes the issue.

This fix fixes 30560.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>