Adding no_rocm tag to //tensorflow/python/saved_model:load_test
This is a CPU only test, but fails in ROCm CI after the 210816 weekly sync. We get the following error

```
======================================================================
ERROR: test_load_registered_ReloadThrice (__main__.LoadTest)
LoadTest.test_load_registered_ReloadThrice
test_load_registered_ReloadThrice(cycles=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/absl_py/absl/testing/parameterized.py", line 282, in bound_param_test
    return test_method(self, **testcase_params)
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/org_tensorflow/tensorflow/python/saved_model/load_test.py", line 2090, in test_load_registered
    class Module(tracking.AutoTrackable):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/org_tensorflow/tensorflow/python/saved_model/registration.py", line 97, in decorator
    registered_name, _CLASS_REGISTRY[registered_name]))
ValueError: Custom.Module has already been registered to (None, <class '__main__.LoadTest.test_load_registered.<locals>.Module'>)

======================================================================
ERROR: test_load_registered_ReloadTwice (__main__.LoadTest)
LoadTest.test_load_registered_ReloadTwice
test_load_registered_ReloadTwice(cycles=2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/absl_py/absl/testing/parameterized.py", line 282, in bound_param_test
    return test_method(self, **testcase_params)
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/org_tensorflow/tensorflow/python/saved_model/load_test.py", line 2090, in test_load_registered
    class Module(tracking.AutoTrackable):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/saved_model/load_test.runfiles/org_tensorflow/tensorflow/python/saved_model/registration.py", line 97, in decorator
    registered_name, _CLASS_REGISTRY[registered_name]))
ValueError: Custom.Module has already been registered to (None, <class '__main__.LoadTest.test_load_registered.<locals>.Module'>)

----------------------------------------------------------------------
Ran 298 tests in 68.422s

FAILED (errors=2, skipped=6)
```

This a new test that was added to the upstream repo during the past week (see commit : https://github.com/tensorflow/tensorflow/commit/9861876978f66073ebdfa6143b4c330ce5910dd6 ), and I suspect this has never passed.

For now, we will asume that the failure is not ROCm specific (cannot be, since it occurs in a non-ROCm build in our CI), and that it will be fixed soon in the upstream repo.