Fix build
The build was broken:

error: weak declaration of 'tensorflow::npd::kTfNextPluggableDeviceUseCApi' must be public

This is because weak implies static. Fix it by explicitly declare as extern.

PiperOrigin-RevId: 531785697