Wrong Code in example in Programmer's guide
In Programmer's guide Variable section
the `assignment` variable is a `tf.Tensor` and should use `.eval()` instead of  `.run()`

Otherwise, this code would produce an error:
```
AttributeError: 'Tensor' object has no attribute 'run'
```