Fix name collision in for-range loop between the container and the element (NFC)
This breaks the build with some old GCC version:

  error: use of 'handle_data' before deduction of 'auto'

PiperOrigin-RevId: 397338802
Change-Id: I4634c287e88a216201b047253acbea7e33f65ec2