reverting psutil version to 5.6.3
psutil package was updated to 5.6.4 on 11/04/2019, and is causing in the following error during executiion of the install/install_pip_packages.sh script.

```
 Downloading https://files.pythonhosted.org/packages/47/ea/d3b6d6fd0b4a6c12984df652525f394e68c8678d2b05075219144eb3a1cf/psutil-5.6.4.tar.gz (447kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
[91m    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip-19.3.1-py2.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpEtHc7B
         cwd: /tmp/pip-install-ztdvSK/psutil
    Complete output (2 lines):
    running dist_info
    error: 'egg_base' must be a directory name (got `/tmp/pip-modern-metadata-rzVBHY`)
```