[ROCm] Fix for a build failure on the ROCm platform - 200323 - 1
The following commit introduces a build error on the ROCm platform

https://github.com/tensorflow/tensorflow/commit/d46aa971be6e7d5a2ec2b9029f38c24bdfb8c277

build error

```
ERROR: /root/tensorflow/tensorflow/lite/delegates/gpu/common/transformations/BUILD:22:1: Couldn't build file tensorflow/lite/delegates/gpu/common/transformations/_objs/add_quant_adjustments/add_quant_adjustments.pic.o: C++ compilation of rule '//tensorflow/lite/delegates/gpu/common/transformations:add_quant_adjustments' failed (Exit 1)
tensorflow/lite/delegates/gpu/common/transformations/add_quant_adjustments.cc: In member function 'virtual tflite::gpu::TransformResult tflite::gpu::AddQuantAdjustments::ApplyToNode(tflite::gpu::Node*, tflite::gpu::GraphFloat32*)':
tensorflow/lite/delegates/gpu/common/transformations/add_quant_adjustments.cc:79:30: error: 'class tflite::gpu::Status' has no member named 'message'
                       status.message())};
                              ^
tensorflow/lite/delegates/gpu/common/transformations/add_quant_adjustments.cc:79:40: error: could not convert '{INVALID, <expression error>}' from '<brace-enclosed initializer list>' to 'tflite::gpu::TransformResult'
                       status.message())};
                                        ^
tensorflow/lite/delegates/gpu/common/transformations/add_quant_adjustments.cc:89:28: error: 'class tflite::gpu::Status' has no member named 'message'
                     status.message())};
                            ^
tensorflow/lite/delegates/gpu/common/transformations/add_quant_adjustments.cc:89:38: error: could not convert '{INVALID, <expression error>}' from '<brace-enclosed initializer list>' to 'tflite::gpu::TransformResult'
                     status.message())};
                                      ^
```

The build error does not seem specific to the ROCm platform, as the cause is the call to a non-existent member method.

The fix is rather trivial...change the call from `status.message` to  `status.error_message`