PR #10504: [GPU] Fix compilation of Triton emitter test.
Imported from GitHub PR https://github.com/openxla/xla/pull/10504

The test currently does not run in OSS builds. Because of the backend [tags](https://github.com/openxla/xla/blob/f8f416b4116b40d1fa7008086f8b6a76ea05ef31/xla/service/gpu/BUILD#L587) it behaves like this:

```
...
INFO: Analyzed target //xla/service/gpu:ir_emitter_triton_test (1 packages loaded, 1 target configured).
INFO: Found 1 test target...
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.
Target //xla/service/gpu:ir_emitter_triton_test up-to-date:
  bazel-bin/xla/service/gpu/ir_emitter_triton_test
INFO: Elapsed time: 0.930s, Critical Path: 0.10s
INFO: 2 processes: 1 internal, 1 local.
INFO: Build completed successfully, 2 total actions
//xla/service/gpu:ir_emitter_triton_test                                 PASSED in 0.0s
```

If backend tags are changed to `backends=["gpu"]` it starts to compile and fails like this:
```
...
xla/service/gpu/ir_emitter_triton_test.cc:917:3: error: use of undeclared identifier 'EXPECT_OK'
  917 |   EXPECT_OK(CreateTritonIrAndFileCheck(kHloText, config, EmitMatMul,
      |   ^
xla/service/gpu/ir_emitter_triton_test.cc:953:3: error: use of undeclared identifier 'EXPECT_OK'
  953 |   EXPECT_OK(CreateTritonIrAndFileCheck(kHloText, config, EmitMatMul,
      |   ^
xla/service/gpu/ir_emitter_triton_test.cc:4041:3: error: use of undeclared identifier 'ASSERT_OK'
 4041 |   ASSERT_OK(
      |   ^
xla/service/gpu/ir_emitter_triton_test.cc:4086:3: error: use of undeclared identifier 'ASSERT_OK'
 4086 |   ASSERT_OK(
...
```

I didn't find any uses of EXPECT_OK / ASSERT_OK without TF_ in other tests.
Copybara import of the project:

--
c0c5dcddae22eede40d9c2af7069558f758714bf by Ilia Sergachev <isergachev@nvidia.com>:

[GPU] Fix compilation of Triton emitter test.

Merging this change closes #10504

PiperOrigin-RevId: 615604708