Fix the issue where distributions.percentile does not support eager mode
This fix tries to address the issue in 23619 where
distributions.percentile in eager mode throws:
```
TypeError: unhashable type: 'list'
```
The issue is that ` [x, q]` should be passed as `values`,
not name default. This fix fixed the issue.

This fix fixes 23619

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>