Updating tensorflow/compiler/xla/service/gpu/cusolver_context.cc to the rocblas_wrapper, instead of calling rocblas API directly.
My first attempt was to re-use the wrapper in the `rocblas_wrapper.h` file, but that resulted in the following compile errors (when running unit tests)

```
...
...
ERROR: /workspace/tensorflow/compiler/xla/service/gpu/tests/BUILD:613:13: Couldn't build file tensorflow/compiler/xla/service/gpu/tests/hlo_to_llvm_ir: Linking of rule '//tensorflow/compiler/xla/service/gpu/tests:hlo_to_llvm_ir' failed (Ex\
it 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-gpu-single/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \
  exec env - \
    LD_LIBRARY_PATH='' \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    ROCBLAS_TENSILE_LIBPATH=/opt/rocm-4.2.0/lib/library \
    ROCM_PATH=/opt/rocm-4.2.0 \
    TF2_BEHAVIOR=1 \
  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/tests/hlo_to_llvm_ir-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/stream_executor/rocm/_objs/rocblas_plugin/rocm_blas.o: multiple definition of 'tensorflow::wrap::DynLoadShim__rocblas_create_handle::kName'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/_objs/cusolver_context/cusolver_context.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/stream_executor/rocm/_objs/rocblas_plugin/rocm_blas.o: multiple definition of 'tensorflow::wrap::DynLoadShim__rocblas_destroy_handle::kName'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/_objs/cusolver_context/cusolver_context.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/stream_executor/rocm/_objs/rocblas_plugin/rocm_blas.o: multiple definition of 'tensorflow::wrap::DynLoadShim__rocblas_set_stream::kName'
...
...
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/_objs/cusolver_context/cusolver_context.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-opt/bin/tensorflow/stream_executor/rocm/_objs/rocblas_plugin/rocm_blas.o: multiple definition of 'tensorflow::wrap::rocblas_snrm2'
/usr/bin/ld.gold: bazel-out/k8-opt/bin/tensorflow/compiler/xla/service/gpu/_objs/cusolver_context/cusolver_context.o: previous definition here
collect2: error: ld returned 1 exit status
...
```

The error is legit and can be worked around by making the wrapper implementation a templated function, instead of a functor object. For example, see the implementation of the rocsolver wrapper in `rocsolver_wrapper.h`. Going that route did not work here because
* the `wrap::rocblas_*` APIs (which becomes templated functions) are passed as arguments to another templated function ( `DoBlasInternal`) which the compiler does not like and errors out on
* The rocblas API `rocblas_gemm_ex` is both a function (with N args) and a macro (with N+2 arguments) and this also seem to confuse the compiler causing it to error out.

```
...
Execution platform: @local_execution_config_platform//:platform
In file included from tensorflow/stream_executor/rocm/rocm_blas.cc:16:0:
./tensorflow/stream_executor/rocm/rocblas_wrapper.h:260:1: error: macro "rocblas_gemm_ex" requires 25 arguments, but only 1 given
 FOREACH_ROCBLAS_API(ROCBLAS_API_WRAPPER)
 ^~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocblas_wrapper.h:260:1: error: macro "rocblas_gemm_ex" requires 25 arguments, but only 1 given
./tensorflow/stream_executor/rocm/rocblas_wrapper.h:52:30: error: expected initializer before '->' token
   auto api_name(Args... args)->decltype(::api_name(args...)) {                \
                              ^
./tensorflow/stream_executor/rocm/rocblas_wrapper.h:52:30: note: in definition of macro 'ROCBLAS_API_WRAPPER'
   auto api_name(Args... args)->decltype(::api_name(args...)) {                \
                              ^~
./tensorflow/stream_executor/rocm/rocblas_wrapper.h:260:1: note: in expansion of macro 'FOREACH_ROCBLAS_API'
 FOREACH_ROCBLAS_API(ROCBLAS_API_WRAPPER)
 ^
tensorflow/stream_executor/rocm/rocm_blas.cc: In member function 'virtual bool stream_executor::gpu::ROCMBlas::DoBlasAsum(stream_executor::Stream*, tensorflow::uint64, const stream_executor::DeviceMemory<float>&, int, stream_executor::DeviceMemory<float>*)':
tensorflow/stream_executor/rocm/rocm_blas.cc:215:69: error: no matching function for call to 'stream_executor::gpu::ROCMBlas::DoBlasInternal(<unresolved overloaded function type>, stream_executor::Stream*&, bool, tensorflow::uint64&, const float*, int&, float*)'
                         GpuMemory(x), incx, GpuMemoryMutable(result));
                                                                     ^
In file included from tensorflow/stream_executor/rocm/rocm_blas.cc:18:0:
./tensorflow/stream_executor/rocm/rocm_blas.h:111:8: note: candidate: template<class FuncT, class ... Args> bool stream_executor::gpu::ROCMBlas::DoBlasInternal(FuncT, stream_executor::Stream*, bool, Args ...)
   bool DoBlasInternal(FuncT rocblas_func, Stream *stream,
        ^~~~~~~~~~~~~~
./tensorflow/stream_executor/rocm/rocm_blas.h:111:8: note:   template argument deduction/substitution failed:
tensorflow/stream_executor/rocm/rocm_blas.cc:215:69: note:   couldn't deduce template parameter 'FuncT'
                         GpuMemory(x), incx, GpuMemoryMutable(result));
                                                                     ^
...
```

Thus the eventual decision to copy-paste the rocblas wrapper implementation in the `cusolver_context.cc` file, to avoid all the errors above.