Use the updated GraphDef (with e.g. placeholders resolved) instead of the original FunctionDef when determining reachable functions in PFLR (process_function_library_runtime). This allows reachability analysis to find wrapped functions.
Without the accompanying fix, the new test will fail with the error:

```
  FailedPreconditionError: {{function_node __wrapped__MapDataset_Targuments_0}}
  Could not find required function definition __inference_Dataset_map_square_11
  [[{{node MapDataset}}]] [Op:MapDataset]
```

PiperOrigin-RevId: 384722451
Change-Id: I558a918fb3f258dbb6f55b92f4b73d79beccaa11