Skipping java unit-tests for the "Ubuntu-CPU" CI run.
These tests are failing with what seems to be a configuration/setup error

```
ERROR: /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/external/bazel_tools/tools/jdk/BUILD:350:14: Couldn't build file external/bazel_tools/tools/jdk/platformclasspath.jar: Action external/bazel_tools/tools/jdk/platformclasspath.jar failed (\
Exit 1): java failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow && \
  exec env - \
  external/local_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions '--add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED' -cp bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/tools/jdk/platformclasspath_classes:external/local_jdk/lib/tools.\
jar DumpPlatformClassPath bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/tools/jdk/platformclasspath.jar external/remotejdk11_linux)
Execution platform: @local_execution_config_platform//:platform
Exception in thread "main" java.lang.AssertionError:
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
        at DumpPlatformClassPath.writeEntries(DumpPlatformClassPath.java:136)
        at DumpPlatformClassPath.writeClassPathJars(DumpPlatformClassPath.java:174)
        at DumpPlatformClassPath.dumpJDK8BootClassPath(DumpPlatformClassPath.java:77)
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:65)
```

We do not really need to test the java unit-tests in this CI run, as this CI run is just to check the sanity of the default CPU / non-ROCm build