Add a few more missing `#include <cmath>` lines to fix MSVC
Fixes MSVC builds failing with

```
error C2039: 'copysign': is not a member of '`global namespace''
```

PiperOrigin-RevId: 427217488
Change-Id: I65072ec7fc7a42a477fcf553fa1c1499a15ac93a