PR #23619: Fix the EmitSort checking after enabling NVLS and user buffer
Imported from GitHub PR https://github.com/openxla/xla/pull/23619

There is a reported bug from NVIDIA that running Midjourney model triggers XLA error after enabling NVLS and user buffer by setting NCCL_NVLS_ENABLE=1 and --xla_gpu_enable_nccl_user_buffers=true:
```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: RET_CHECK failure (external/xla/xla/service/gpu/ir_emitter_unnested.cc:1676) LayoutUtil::LayoutsInShapesEqual(keys_shape, sort->operand(i)->shape()).
```
This is because after enabling NVLS and user buffer, one of the operand of `sort` operation is from a different memory space (user buffer), and the previous `LayoutsInShapesEqual` check is too strong to pass as it also checks if operands are from the same memory space.

This MR makes the sort layout check weaker as operands do not have to be in the same memory space as long as they all on the device.
Copybara import of the project:

--
826535264624142999164132f3a873be06019279 by Chenhao Jiang <chenhaoj@nvidia.com>:

Making the sort layout check weaker as operands do not have to be in the same memory space as long as they all on the device.

Merging this change closes #23619

PiperOrigin-RevId: 738761820