Fix build failure with v2 config
While trying to build tensorflow with v2 config:
```
bazel build -s --verbose_failures --config=opt --config=v2 //tensorflow/tools/pip_package:build_pip_package
```

The following failure was encountered:
```
ERROR: /home/ubuntu/tensorflow/tensorflow/core/kernels/BUILD:6800:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:summary_kernels':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/summary_kernels.cc':
  'tensorflow/contrib/tensorboard/db/schema.h'
  'tensorflow/contrib/tensorboard/db/summary_db_writer.h'
  'tensorflow/core/kernels/summary_interface.h'
  'tensorflow/contrib/tensorboard/db/summary_file_writer.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

The issue was that summary_kernels.cc depends on tensorflow/contrib/tensorboard
no matter if v1 or v2 is selected.

This fix fixes the issue so that it is possible to build tensorflow with v2 config

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>