Fix for broken ROCm CSB - 200309
This commit fixes a build error in the TF ROCm build introduced by the following commit

https://github.com/tensorflow/tensorflow/commit/00e148f41dbc01087ab40bbe588c538d9589f394#diff-903807f7382f5e9f100e3aadee096f3a

TF ROCm build started failing with the followign error:

```
ERROR: /workspace/tensorflow/compiler/mlir/xla/BUILD:135:1: Couldn't build file tensorflow/compiler/mlir/xla/_objs/xla_legalize_tf_with_tf2xla/legalize_tf_with_tf2xla.o: C++ compilation of rule '//tensorflow/compiler/mlir/xla:xla_legalize_tf_with_tf2xla' failed (Exit 1)
tensorflow/compiler/mlir/xla/transforms/legalize_tf_with_tf2xla.cc:18:23: fatal error: string_view: No such file or directory
compilation terminated.
```

The fix was to change the include for the string_view header from

```
#include <string_view>
```

to

```
#include "absl/strings/string_view.h"
```