Add missing imports that should fix the MSVC bug
```
error C2039: 'copysign': is not a member of '`global namespace''
```

PiperOrigin-RevId: 427269276
Change-Id: Ife6b888f30e0ebf20a35c8ebfdce4e38575979f7