[ROCm] Fix for ROCM CSB breakage - 210322
The following commit adds GPU support for int32/int64 support for the Unique/UniqueWithCounts ops, but breaks ROCm build in the process

https://github.com/tensorflow/tensorflow/commit/02585ace8ca787613637713aebfd581a6dc2a12a

```
tensorflow/core/kernels/unique_op_gpu.cu.cc:292:9: error: no matching constructor for initialization of 'gpuprim::TransformInputIterator<int, SegmentIndicatorFunctor<unsigned long, int>, gpuprim::CountingInputIterator<int>>' (aka 'transform_iterator<rocprim::counting_iterator<int, long>, tensorflow::(anonymous namespace)::SegmentIndicatorFunctor<unsigned long, int>, int>')
        segment_indicator_iter(0, {sorted_input_ptr});
        ^                      ~~~~~~~~~~~~~~~~~~~~~
tensorflow/core/kernels/unique_op_gpu.cu.cc:176:12: note: in instantiation of member function 'tensorflow::UniqueOpGPU<unsigned long, int>::ComputeAsync' requested here
  explicit UniqueOpGPU(OpKernelConstruction* context)
           ^
tensorflow/core/kernels/unique_op_gpu.cu.cc:461:27: note: in instantiation of member function 'tensorflow::UniqueOpGPU<unsigned long, int>::UniqueOpGPU' requested here
TF_CALL_REAL_NUMBER_TYPES(REGISTER_UNIQUE_GPU);
```

This PR/commit disables ROCm support for newly added ops to get the CSB passing again. We are looking into resolving the build errors, and will file a separate PR to re-enable ROCm functionality for the same. This PR commit also adds the `no_rocm` tag to a couple of unit tests that start failing as a consequence of lack of ROCm support for these ops.

```
//tensorflow/python/keras/optimizer_v2:adamax_test_gpu                   FAILED in 3 out of 3 in 7.0s
//tensorflow/python/training:adam_test_gpu                               FAILED in 3 out of 3 in 6.3s
```