Fix issue in tf.ones where tf.quint8/quint16 does not work in graph mode
This PR tries to address the issue where tf.ones where tf.quint8/quint16 does not work in graph mode:
```
>>> @tf.function(autograph=False)
... def f():
...     return tf.ones([], tf.qint16)
...
>>> f()
...
...
    allow_broadcast=allow_broadcast))
  File "/Library/Python/3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 456, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Library/Python/3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 336, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected qint16, got 1 of type 'int' instead.
```

The reason is similiar to the internal error encountered in 41421.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>