TF Eager: Improve the error message so that user know what are the numbers for.
I got the following error message which is really confusing:
ValueError: Arguments and signature arguments do not match: 4 3

The error happens under a few abstractions so pretty hard to understand which one is which.

PiperOrigin-RevId: 260938035