[ROCm] Fix for ROCm CSB breakage - 210311
The following commit breaks the ROCm CSB (errors while running GPU unit tests)

https://github.com/tensorflow/tensorflow/pull/47398

```
ERROR: /root/tensorflow/tensorflow/compiler/xla/service/gpu/tests/BUILD:573:13: undeclared inclusion(s) in rule '//tensorflow/compiler/xla/service/gpu/tests:hlo_to_llvm_ir':
this rule is missing dependency declarations for the following files included by 'tensorflow/compiler/xla/service/gpu/tests/hlo_to_llvm_ir.cc':
  'tensorflow/compiler/xla/service/gpu/nvptx_compiler.h'
Target //tensorflow/compiler/xla/service/gpu/tests:constant.hlo.test failed to build
```

This PR/commit fixes the ROCm build, by making the newly added functionality specific to the TF CUDA build.

Long term, we need to add similar capability to the ROCM side, but for now this workaround is needed to get the ROCm CSB working again.