Adding no_rocm tag to //tensorflow/python/util:traceback_utils_test
This is CPU only tests, but fails in ROCm CI with the following error

```
...
...
Traceback (most recent call last):
  File "/home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61$
    self.assert_trace_line_count(fn, count=15, filtering_enabled=True)
  File "/home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61$
    traceback_utils.enable_traceback_filtering()
  File "/home/jenkins/workspace/tensorflow/github-prs-rocmfork-develop-upstream/rocm-latest-ubuntu-cpu/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61$
    f'Traceback filtering is only available with Python 3.7 or higher. '
RuntimeError: Traceback filtering is only available with Python 3.7 or higher. This Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0]
...
...
```

The reason for the failure is because ROCm CI still uses Python 3.6 in it's CI containers and the test seems to need Python 3.7 or higher.

So adding `no_rocm` tag to the test for now. It should be removed once we have upted ROCm CI to use newer Python version