Temporary hack to fix for TF build failure with ROCm 5.2
The `gpu_solvers.h` header file has ROCm version specific code in it which is controlled via `#if (TF_ROCM_VERSION >= ...)`. Currently this code is not working as it should because the `gpu_solvers.h` header does not include the `rocm/rocm_config.h` header, which has the definition for the `TF_ROCM_VERSION` macro. This results in the `#else` block getting picked always.

A different commit (https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/pull/1607/commits/a7a2b8d2f08f2cceca5ad6fcb2b4e131d6cfbcb7), to fix some TF build failures with ROCm 5.2, includes the `rocm/rocm_config.h` header file. That results in the correct (ROCM version dependent) branch being picked, but that also seems to introduce build failures like the following

```
clang-14: warning: argument unused during compilation: '-fcuda-flush-denormals-to-zero' [-Wunused-command-line-argument]
In file included from tensorflow/core/kernels/unique_op_gpu_3.cu.cc:19:
In file included from ./tensorflow/core/kernels/unique_op_gpu.cu.h:32:
./tensorflow/core/util/gpu_solvers.h:138:23: error: unknown type name 'hipsolverOperation_t'
using gpuSolverOp_t = hipsolverOperation_t;
                      ^
./tensorflow/core/util/gpu_solvers.h:139:25: error: unknown type name 'hipsolverFillMode_t'
using gpuSolverFill_t = hipsolverFillMode_t;
                        ^
./tensorflow/core/util/gpu_solvers.h:140:25: error: unknown type name 'hipsolverSideMode_t'
using gpuSolverSide_t = hipsolverSideMode_t;
                        ^
./tensorflow/core/util/gpu_solvers.h:285:22: error: unknown type name 'gpuSolverOp_t'
  Status Getrs(const gpuSolverOp_t trans, int n, int nrhs, Scalar* A, int lda,
                     ^
./tensorflow/core/util/gpu_solvers.h:300:16: error: unknown type name 'gpuSolverFill_t'
  Status Potrf(gpuSolverFill_t uplo, int n, Scalar* dev_A, int lda,
               ^
./tensorflow/core/util/gpu_solvers.h:324:23: error: unknown type name 'gpuSolverFill_t'
  Status PotrfBatched(gpuSolverFill_t uplo, int n,
                      ^
./tensorflow/core/util/gpu_solvers.h:352:16: error: unknown type name 'gpuSolverSide_t'
  Status Unmqr(gpuSolverSide_t side, gpuSolverOp_t trans, int m, int n, int k,
               ^
./tensorflow/core/util/gpu_solvers.h:352:38: error: unknown type name 'gpuSolverOp_t'
  Status Unmqr(gpuSolverSide_t side, gpuSolverOp_t trans, int m, int n, int k,
                                     ^
./tensorflow/core/util/gpu_solvers.h:367:16: error: unknown type name 'gpuSolverOp_t'
  Status Heevd(gpuSolverOp_t jobz, gpuSolverFill_t uplo, int n, Scalar* dev_A,
               ^
./tensorflow/core/util/gpu_solvers.h:367:36: error: unknown type name 'gpuSolverFill_t'
  Status Heevd(gpuSolverOp_t jobz, gpuSolverFill_t uplo, int n, Scalar* dev_A,
```

http://ml-ci.amd.com:21096/job/tensorflow/job/github-prs-rocmfork-develop-upstream/job/rocm-latest-ubuntu-gpu-single/760/
http://ml-ci.amd.com:21096/job/tensorflow/job/github-prs-rocmfork-develop-upstream/job/rocm-latest-ubuntu-gpu-multi/793/

The fix for the build failures is non-trivial and needs to be addressed as a separate PR. This commit should be reverted in that future PR, which will fix the above build failure.

The other commit to resolve the ROCm 5.2 build failure is needed to unblock QA from testing ROCm 5.2, and hence the need to for this short-lived hack.