Adding `no_rocm` tag to //tensorflow/python/kernel_tests:extract_image_patches_grad_test_gpu
This unit-test starts to fail when we switch from ROCm 4.0.1 to ROCm 4.1.0

QA did not detect this regression because this test passes in the branch they were using to qualify ROCm 4.1.0 ( `develop-upstream-QA-rocm41` )

In addition to other changes (between `develop-upstream-QA-rocm41` and tip of `develop-upstream`), the testcase itself seems to have changed. We need to root-cause the regression, fix it and re-enable the test.

Copy-pasting the error log here for reference

```
======================================================================
FAIL: test_AllNone_Gradient (__main__.ExtractImagePatchesGradTest)
test_AllNone_Gradient (__main__.ExtractImagePatchesGradTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 185, in test_AllNone_Gradient
    self._VariableShapeGradient([None, None, None, None])
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 173, in _VariableShapeGradient
    self.assertLess(err, 1e-4)
AssertionError: nan not less than 0.0001

======================================================================
FAIL: test_BxxC_Gradient (__main__.ExtractImagePatchesGradTest)
test_BxxC_Gradient (__main__.ExtractImagePatchesGradTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 176, in test_BxxC_Gradient
    self._VariableShapeGradient([-1, None, None, -1])
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 173, in _VariableShapeGradient
    self.assertLess(err, 1e-4)
AssertionError: 0.4175793528556824 not less than 0.0001

======================================================================
FAIL: test_xHWx_Gradient (__main__.ExtractImagePatchesGradTest)
test_xHWx_Gradient (__main__.ExtractImagePatchesGradTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 179, in test_xHWx_Gradient
    self._VariableShapeGradient([None, -1, -1, None])
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/python/kernel_tests/extract_image_patches_grad_test_gpu.runfiles/org_tensorflow/tensorflow/python/kernel_tests/extract_image_patches_grad_test.py", line 173, in _VariableShapeGradient
    self.assertLess(err, 1e-4)
AssertionError: 0.2977283000946045 not less than 0.0001

----------------------------------------------------------------------
Ran 7 tests in 406.984s

FAILED (failures=3, skipped=1)
================================================================================
```