[tf.data] Improve error message when dataset serialization fails.
Previously we would get an error along the lines of

NotFoundError: Resource localhost/hash_table_6d5754e2-c5bd-4c7f-8f99-5aa8782dd5a8/ResourceBase does not exist.

Now the error looks like

FailedPreconditionError: Serialization error while trying to register a dataset with tf.data service. The dataset may depend on a resource located on a different device. To address this, call `register_dataset` from the device with the resource, then use `from_dataset_id` to create per-device datasets. Original error: Invalid argument: Trying to access resource hash_table_8945247c-dee3-4c71-a49b-1d9d8aa5f13c located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:CPU:1

To get the information about which device the resource is being accessed from, this CL plumbs the OpKernelContext through the SerializationContext.

PiperOrigin-RevId: 380641324
Change-Id: I995dccb2766ac526c1154e3e8627e30e7cf7630a