[mlir/lite] flatbuffer_export: Improve message for StableHLO ops
To convert StableHLO ops, Translator::Translate must be called with
serialize_stablehlo_ops=true.  If using TfLiteConverter, this is done by
setting
target_spec.suggested_ops={tf.lite.OpsSet.EXPERIMENTAL_STABLEHLO_OPS}.

However, this was not obvious from the old error message of

```
error: 'vhlo.reduce_v1' op is not part of the vhlo support yet.
```

which was also misleading, since `vhlo.reduce_v1` is, in fact, supported
with the right options.

The new error message is:

```
error: 'vhlo.reduce_v1' op is part of the vhlo support, but
Translator::Translate was called with serialize_stablehlo_ops=false.  If using
TfLiteConverter, set
target_spec.suggested_ops={tf.lite.OpsSet.EXPERIMENTAL_STABLEHLO_OPS}.
```
PiperOrigin-RevId: 728185965