Fix `ram_file_block_cache_test` on Windows.
When I imported #41235 I followed the linter warnings for Linux but this inadvertendly broke Windows

```
tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc(230): error C3493: 'file_size' cannot be implicitly captured because no default capture mode has been specified

tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc(237): error C2664: 'tf_gcs_filesystem::RamFileBlockCache::RamFileBlockCache(const tf_gcs_filesystem::RamFileBlockCache &)': cannot convert argument 4 from 'int' to 'tf_gcs_filesystem::RamFileBlockCache::BlockFetcher'

tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc(238): note: No constructor could take the source type, or constructor overload resolution was ambiguous

.\tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache.h(52): note: see declaration of 'tf_gcs_filesystem::RamFileBlockCache::RamFileBlockCache'

tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc(532): error C3493: 'block_size' cannot be implicitly captured because no default capture mode has been specified

tensorflow/c/experimental/filesystem/plugins/gcs/ram_file_block_cache_test.cc(568): error C3493: 'block_size' cannot be implicitly captured because no default capture mode has been specified
```

PiperOrigin-RevId: 320695991
Change-Id: Ib2cd1c9ed37c92702e8341c0309819373bae7445