Fix build to work in Android Studio
Tested on Android Studio 3.2.1 with emulator Pixel XL API 24.

Here is a list of six of the errors resolved by these updates:

1) Disable Jack to fix compile errors.

Error was:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformJackWithJackForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	... (truncated)

Source: https://developer.android.com/studio/write/java8-support#disable_jack

2) Update the plugin to support Java 8 features.

Error was:
Jack is required to support java 8 language features. Either enable Jack or remove sourceCompatibility JavaVersion.VERSION_1_8.

Source: https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

3) Update repositories to include google()

Error was:
Could not find com.android.tools.build:aapt2:3.2.1-4818971.

4) Change 'compile' to 'implementation' in build.gradle

Error was:
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

5) Update build tools and support library versions

Error was:
The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.2.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Update Build Tools version and sync project
Open File