micro: fix null-dereference build warning/error on g++ 10.2
Without the added ENSURE, g++ flags an:

    error: potential null pointer dereference [-Werror=null-dereference]

in both of these locations while building from the Makefile a la:

    % g++ --version
    g++ (Debian 10.2.0-19) 10.2.0

    % make -f tensorflow/lite/micro/tools/make/Makefile test

which breaks the build.

Fixes #45381.