Fix for JAX failure on ROCm due to commit ba57ae7f24743e684accef3521485a24c1235186.
When running JAX unit tests, the following error was observed:

ImportError: /usr/local/lib/python3.9/dist-packages/jaxlib/xla_extension.so: undefined symbol: _ZN10tensorflow33tensor_float_32_execution_enabledEv

This PR fixes the error.