Typo, causing AttributeError
$ ~/mnist $ python convolutional.py
Traceback (most recent call last):
  File "convolutional.py", line 316, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "convolutional.py", line 123, in main
    train_labels_filename = maybe_download('train-labels-idx1-ubyte.gz')
  File "convolutional.py", line 62, in maybe_download
    size = f.Size()
AttributeError: 'GFile' object has no attribute 'Size'