potential workaround for a bunch of unit test failures.
After this week's upstream merge, a bunch of unit tests in the

- tensorflow/examples/adding_an_op
- tensorflow/examples/autograph/integration_tests
- tensorflow/examples/speech_commands
- tensorflow/examples/tutorials/mnist

dirs started to fail with the following error:

```
ImportError: cannot import name 'capture_dependencies'
```

This is because there seems to be a circular dependency when trying to import "checkpointable.util" (as can be seen in the full error lof below)

Don't have a proper solution for this issue yet...this commit is just a potential workaround to get these unit tests passing
(the workaround is to break the cyclic depedency by skipping the import of "mirrored_strategy" whenin ROCm mode)

```
Traceback (most recent call last):

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/examples/tutorials/mnist/fully_connected_feed.py", line 28, in <module>
    import tensorflow as tf

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 72, in <module>
    from tensorflow.python.ops.standard_ops import *

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/ops/standard_ops.py", line 97, in <module>
    from tensorflow.python.ops.template import *

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/ops/template.py", line 30, in <module>
    from tensorflow.python.training.checkpointable import util as checkpointable_util

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/training/checkpointable/util.py", line 42, in <module>
    from tensorflow.python.training import optimizer as optimizer_lib

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/training/optimizer.py", line 27, in <module>
    from tensorflow.python.distribute import distribute_lib

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/distribute/__init__.py", line 24, in <module>
    from tensorflow.python.distribute import mirrored_strategy

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/distribute/mirrored_strategy.py", line 27, in <module>
    from tensorflow.python.distribute import cross_device_ops as cross_device_ops_lib

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/distribute/cross_device_ops.py", line 25, in <module>
    from tensorflow.python.distribute import cross_device_utils

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/python/distribute/cross_device_utils.py", line 35, in <module>
    from tensorflow.contrib import rccl as nccl_ops

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 28, in <module>
    from tensorflow.contrib import checkpoint

  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/k8-opt/bin/tensorflow/examples/tutorials/mnist/fully_connected_feed_test.runfiles/org_tensorflow/tensorflow/contrib/checkpoint/__init__.py", line 59, in <module>
    from tensorflow.python.training.checkpointable.util import capture_dependencies

ImportError: cannot import name 'capture_dependencies'
```

https://github.com/tensorflow/tensorflow/commit/2114ed7447c8239531aae073336140c8ca861303