Fix cmake Dockerfile issue on Linux
When running cmake on Linux with (clean build with no cached docker images):
```
tensorflow/tools/ci_build/ci_build.sh CMAKE tensorflow/tools/ci_build/builds/cmake.sh
```

The following isse was encountered:
```
Step 11/13 : RUN pip install --upgrade termcolor
 ---> Running in 838167596eb6
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz
  ......
  ......
  ......
  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for termcolor
```

This fix adds the missing `pip install wheel`

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>