Merge 1.4 branch back into master (#14305)
* Update RELEASE NOTES for TensorFlow 1.4

* Update the version strings for TF 1.4-rc0.

* Update version strings in POM files missed by update script.

* Pin TensorBoard 0.4 to TensorFlow 1.4

* Fixing the name of the disabled test. (#13592)

* Revert "Implementing ghost batch norm as defined in https://arxiv.org/pdf/1705.08741."

This reverts commit 125f7afa4a483855dc75791445d2dea64587876a.

* Disable iterator_ops_test on Windows for 1.4 release (#13609)

* Disable failing Windows tests for r1.4 release.

testRemoteIteratorUsingRemoteCallOpDirectSessionGPUCPU test is failing
with "TypeError: only integer scalar arrays can be converted to a scalar
index" on the Windows GPU Release bot. Disabling test.

* Fix typo.

* Also disalbe iterator_ops_test from contrib/.

* Add contributing authors to 1.4 Release notes.

Thanks!

* Fixes to authors.

Removed duplicate and removed googler from contributing author list.

* Fixes and additions to release notes.

Added line about Keras moving into core.
Added line about CUDA/cuDNN versions.
Added line about custom ops.

* Fixing a master regression (#13562)

* Update version strings for 1.4.0rc1

* Remaining cherry-picks for 1.4.0rc1 (#13700)

* Java: Tweak to address some Javadoc errors.

PiperOrigin-RevId: 171987329

* Fix S3 BUILD not including files explicitly.

This causes remote builds to fail since they AWS headers were missing.

PiperOrigin-RevId: 171718021

* Add missing default config setting in aws.BUILD (#13662)

* Remove setting AWS logging for S3 file system.

Was causing issues with tests. Can repro test failures on Macs by running...

bazel test --config=s3  --cache_test_results=no --test_output=streamed
//tensorflow/core/kernels:control_flow_ops_test

Possible reason for error is symbol collision with AWS logging code.
One possible solution would be to split out another shared object for
the S3 filesystem op which does not link in libtensorflow_framework.so.
This is done, for example, by libforestprotos.so in
tensorflow/contrib/tensor_forest/BUILD

PiperOrigin-RevId: 171246381

* Relanding change to add config to enable S3 file system support.

Pass --config=s3 argument to Bazel to build with S3 file system support.
Change was originally rolled back due to a failure it caused in
//tensorflow/core/kernels:control_flow_ops_test on Macs which is now fixed.

PiperOrigin-RevId: 171579378

* Update release notes about Amazon S3 file system support being default.

* Add documentation to sloppy_interleave function

PiperOrigin-RevId: 171303413

* Add `cudnn_rnn_ops` to the Windows build

Fixes #13696.

* Creating a patch for the wrong links that still point to dev. (#13753)

* tfdbg release notes in r1.4

* Fix ambiguous type comparison in s3_crypto.cc (#13758)

tensorflow/contrib/s3/s3_crypto.cc(74): error C2666:
'std::fpos<_Mbstatet>::operator ==': 3 overloads have similar conversions
could be 'bool std::fpos<_Mbstatet>::operator ==(std::streamoff) const'
or 'bool std::fpos<_Mbstatet>::operator ==(const std::fpos<_Mbstatet> &)
We were seeing this compilation error on Windows builds.

* Set estimator run_config default random seed to None. This will make it aligned with other parts of the TF. Many users are not aware of impact of non-random seed. For example it may lead to train only on a small fraction of training data due to preemptions.
We're changing default behavior since we consider it as a bug fix.

PiperOrigin-RevId: 172519268

* Move global_step_read dependency to model_fn instead of input_fn.

PiperOrigin-RevId: 172366972

* [tf.data] Fix broken implementation of `Dataset.from_generator()` on Windows.

Due to a mix-up between NumPy's default array element type for a Python `int` on Windows and Linux, a tf.py_func() in `Dataset.from_generator()` would appear to return the wrong type on Windows (np.int32 instead of np.int64).

All code using `Dataset.from_generator()` on Windows was previously broken. This change fixes both `tf.data.Dataset.from_generator()` and `tf.contrib.data.Dataset.from_generator()`. It also enables test coverage for this method on Windows, which should prevent future breakage.

PiperOrigin-RevId: 172346533

* Update RELEASE notes for change to run_config random seed.

* Disable probable timeout flake on Ubuntu machines.

PiperOrigin-RevId: 172408922

* Disabling failing contrib tests.

* Disable S3 on Windows due to build issues.

* Update serving_input_fn argument name to serving_input_receiver_fn

PiperOrigin-RevId: 172787460

* Update the C++ API guide (#13858)

- Adds the standard warning at the top that people may want the master branch
- Includes a documentation fix for 1.4 (cc_binary -> tf_cc_binary to avoid
  undefined symbols).

* Add known Dataset issue to RELEASE.md. (#13870)

Adding info about issue using Unicode strings with Datasets.

* Add link to datasets doc (#14009)

* Fix typos in Linear Model Tutorial samples

1. test_file_name is undefined (should be test_file.name)
2. train_file_name is undefined (should be train_file.name)

PiperOrigin-RevId: 173733442

* Fixing the sources docs in r1.4.

* Remove name_scope from convolutional calls. (#14044)

* Remove name_scope from convolutional calls.

PiperOrigin-RevId: 173171871

* Fix error with cherry-pick.

Somehow missed one of the layer renamings on the quantize_parameterized_test.

* Update version strings to 1.4.

* Resolve //tensorflow relative to tensorflow repo so that tfcompile.bzl can be correctly loaded from another Bazel project (#14103)

* Update install_sources.md

* Update Bazel required version for r1.4.