Rolling forward again (with fixes for new merge conflicts) after spurious auto-rollback. The failing test is just very flaky, and the failures recorded by the autorollback tool seem to be just coincidence.
I have measured the flakiness of this test before and after the alleged culprit CL,
over 2000 runs in each case, and the flakiness was the same to within experimental
error: 83% ± 2% before the alleged culprit CL, and 82% ± 2% after the alleged
culprit CL.
PiperOrigin-RevId: 479292337