Updating the rule for the target `//tensorflow/core/profiler/internal/gpu:device_tracer`
Making the cuda_deps list unconditional. The conditionality check (i.e. whether or not to pick the dependent target) is encompassed within the dependent target rule itself, which allows us to make the cuda_deps list unconditional.

This change was required because an upstream commit ( https://github.com/tensorflow/tensorflow/commit/4379cc4cf623dbfb74521734807988c3b3f2b831 ) which changes the implementation of the `if_cuda_is_configured` and `if_rocm_is_configured` triggered the following bazel error for the rule of the target `//tensorflow/core/profiler/internal/gpu:device_tracer`

```
ERROR: Traceback (most recent call last):
	File "/root/tensorflow/tensorflow/core/profiler/internal/gpu/BUILD", line 30, column 16, in <toplevel>
		tf_cuda_library(
	File "/root/tensorflow/tensorflow/tensorflow.bzl", line 1455, column 19, in tf_cuda_library
		tf_gpu_library(*args, **kwargs)
	File "/root/tensorflow/tensorflow/tensorflow.bzl", line 1445, column 12, in tf_gpu_library
		]) + if_rocm_is_configured(cuda_deps + [
Error: '+' operator applied to incompatible types (select of list, select of select)
```